# Makefile generated by OpenModelica
# Platform: win64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang++ -shared -Xlinker --export-all-symbols
EXEEXT=.exe
DLLEXT=.dll
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}   
CPPFLAGS="-IC:/Users/lenovo/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/C-Sources" -I"C:/Program Files/OpenModelica1.21.0-64bit/include/omc/c" -I"C:/Program Files/OpenModelica1.21.0-64bit/include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=ADM1_P_UIT_real_R2_copia -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=19 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS=-lSimulationRuntimeC -Wl,-Bdynamic -lomcgc -lopenblas -Wl,-B$(OMC_LDFLAGS_LINK_TYPE)  -lstdc++ -Wl,-Bdynamic 
LDFLAGS=-L"C:/Program Files/OpenModelica1.21.0-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.21.0-64bit/lib" -Wl,--stack,16777216,-rpath,"C:/Program Files/OpenModelica1.21.0-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.21.0-64bit/bin" -Wl,-rpath,"C:/Program Files/OpenModelica1.21.0-64bit/lib"  -fopenmp -Wl,-Bstatic -lregex -ltre -lintl -liconv -lexpat -lpthread -loleaut32 -limagehlp -lhdf5 -lz -lszip -Wl,-Bdynamic $(RUNTIME_LIBS) 
DIREXTRA=-L"C:/Users/lenovo/OneDrive - Politecnico di Milano/Work_cloud/DOTTORATO/Modelling/Pilot_plant"
MAINFILE=ADM1_P.UIT_real_R2_copia.c
MAINOBJ=ADM1_P.UIT_real_R2_copia.o
CFILES=ADM1_P.UIT_real_R2_copia_functions.c ADM1_P.UIT_real_R2_copia_records.c \
ADM1_P.UIT_real_R2_copia_01exo.c ADM1_P.UIT_real_R2_copia_02nls.c ADM1_P.UIT_real_R2_copia_03lsy.c ADM1_P.UIT_real_R2_copia_04set.c ADM1_P.UIT_real_R2_copia_05evt.c ADM1_P.UIT_real_R2_copia_06inz.c ADM1_P.UIT_real_R2_copia_07dly.c \
ADM1_P.UIT_real_R2_copia_08bnd.c ADM1_P.UIT_real_R2_copia_09alg.c ADM1_P.UIT_real_R2_copia_10asr.c ADM1_P.UIT_real_R2_copia_11mix.c ADM1_P.UIT_real_R2_copia_12jac.c ADM1_P.UIT_real_R2_copia_13opt.c ADM1_P.UIT_real_R2_copia_14lnz.c \
ADM1_P.UIT_real_R2_copia_15syn.c ADM1_P.UIT_real_R2_copia_16dae.c ADM1_P.UIT_real_R2_copia_17inl.c ADM1_P.UIT_real_R2_copia_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) ADM1_P.UIT_real_R2_copia.makefile ADM1_P.UIT_real_R2_copia_literals.h ADM1_P.UIT_real_R2_copia_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that ADM1_P.UIT_real_R2_copia_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) ADM1_P.UIT_real_R2_copia_functions.h ADM1_P.UIT_real_R2_copia_literals.h $(OFILES)
	$(CC) -I. -o ADM1_P.UIT_real_R2_copia$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)  "-LC:/Program Files/OpenModelica1.21.0-64bit/bin/" "-LC:/Program Files/OpenModelica1.21.0-64bit/lib//omc" "-LC:/Program Files/OpenModelica1.21.0-64bit/lib/" "-LC:/Users/lenovo/AppData/Roaming/.openmodelica/binaries/Modelica" "-LC:/Users/lenovo/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library/mingw64" "-LC:/Users/lenovo/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library/win64" "-LC:/Users/lenovo/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library" -lModelicaExternalC -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f ADM1_P.UIT_real_R2_copia_records.o $(MAINOBJ)

bundle:
	@tar -cvf ADM1_P.UIT_real_R2_copia_Files.tar $(GENERATEDFILES)