/* Additional record code for ADM1_P.UIT_real_R2_copia generated by the OpenModelica Compiler OpenModelica v1.21.0 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "ADM1_P.UIT_real_R2_copia_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

